import Head from 'next/head'
import Navbar from "../components/navbar";
import AvatarChips from '../components/about_feature';
import ImgMediaCard from '../components/menu'
// import AboutInfo from '../components/AboutInfo';

export default function About() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <AboutInfo /> */}
      <Navbar/>
      <h1>About page</h1>
      <AvatarChips/>
      <h3>Menu</h3>
     <div className={styles.menucard}>
     <ImgMediaCard/>
     <ImgMediaCard/>
     <ImgMediaCard/>
     <ImgMediaCard/>
     </div>
    </div>
  )
}
