
import Head from 'next/head'
import { Box } from '@mui/material';
import Navbar from "../components/navbar";

// import ContactInfo from '../components/ContactInfo'

export default function Pizza() {
    return (
        <Box>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <ContactInfo /> */}
            <Navbar/>
            <h1>Pizza page</h1>
        </Box>
    )
}